

# Title: Compiling model results figures into panel plots for publication

# Author: Nina Venuti

# Acknowledgements: sections of code used to plot final results figures
# were adapted from Claire Tortorelli

# Script inputs: a series of data.frames used to plot the results of each
# species-year base model in each iteration of script #6 ("06_results_vis_
# and_interp_SPPCODE.R"). These data.frames include species-year specific
# tables of field-collected data (e.g., "ABCO_data_yr1_full"), as well as 
# tables of predicted mean cone counts across the full spectrum of crown
# volume damage (e.g., "ABCO_myr1_pred_df"), and at specific threshold values 
# (e.g., "ABCO_myr1_pred_df_thresholds"), generated by the Functions F, G1, 
# G2, and H (see the script "04_results_functions.R" for further details). 
# All necessary script inputs should appear in the Environment pane after
# running each, species-specific iteration of script #6.

# Script outputs: 1) two sets of panel plots - the first, displaying 
# predicted cone counts for median-sized ABCOs, PIPJs, and PILAs in both 
# the first and second year after fire, and the second, displaying predicted
# cone counts for the 10th, 50th, and 90th percentile-sized ABCOs, PIPJs, and 
# PILAs in both sample years, and 2) an alternate version of the plot "PILA_
# myr1_plot" (see script "06_results_vis_and_interp_PILA.R"), reformatted
# for publication. All plots are exported as both .png and .pdf files.

library("tidyverse")
library("cowplot")


## creating a panel plot that displays predicted mean cone counts in median-
## sized ABCOs, PIPJs, and PILAs in both the first and second years
## after fire, with one panel for each species (and each panel containing
## two curves - one for each sample year)...

# first, resizing and reformatting each of the median tree plots (originally 
# generated in each, species-specific iteration of script #6), to be 
# compiled into a single panel plot below...

# reformatting the ABCO median tree plot...
ABCO_mediantree_plot_forpanel <- ABCO_mediantree_pred_df_BOTHYRS %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = SampleEffort_yr)) +
  geom_line(linewidth = 0.8) +
  scale_color_manual(values = c("yr1" = "paleturquoise4", 
                                "yr2" = "cadetblue3"),
                     labels = c("year 1",
                                "year 2")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = SampleEffort_yr),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_manual(values = c("yr1" = "paleturquoise4", 
                               "yr2" = "cadetblue3"),
                    labels = c("year 1",
                               "year 2")) +
  geom_point(data = ABCO_mediantree_pred_thresholds_BOTHYRS,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = SampleEffort_yr),
             size = 2) +
  geom_point(data = ABCO_data_yr1_full,
             aes(x = CrownDamage_percentvolume +
                   runif(nrow(ABCO_data_yr1_full), min = -0.75, max = 0.75),
                 y = 1.7),
             shape = "|", 
             size = 2, 
             color = "paleturquoise4") +
  geom_point(data = ABCO_data_yr2,
             aes(x = CrownDamage_percentvolume +
                   runif(nrow(ABCO_data_yr2), min = -0.75, max = 0.75),
                 y = 1.5),
             shape = "|", 
             size = 2, 
             color = "cadetblue3") +
  coord_trans(y = "log") +
  scale_y_continuous(breaks = c(0, 25, 50, 100, 200, 300, 400)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  theme_classic() +
  guides(color = guide_legend(title = "Sample year"),
         fill = guide_legend(title = "Sample year")) + 
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 8, face = "bold",
                                    margin = margin(0, 0.5, 0, 0, "cm")),
        legend.text = element_text(size = 7),
        legend.direction = "horizontal",
        legend.key.size = unit(0.5, "cm"),
        legend.key.spacing.x = unit(0.3, "cm"),
        legend.margin = margin(0, 0, 0, 0, "cm"),
        legend.position = "top",
        legend.justification = "center",
        legend.justification.top = c(0.6))

ABCO_mediantree_plot_forpanel

# extracting the legend from this reformatted plot, for use in the panel
# below...
mediantree_plot_legend <- get_legend(ABCO_mediantree_plot_forpanel)

# resaving the ABCO_mediantree_plot_forpanel without its legend...
ABCO_mediantree_plot_forpanel <- ABCO_mediantree_plot_forpanel +
  theme(legend.position = "none")

ABCO_mediantree_plot_forpanel


# reformatting the PIPJ median tree plot...
PIPJ_mediantree_plot_forpanel <- PIPJ_mediantree_pred_df_BOTHYRS %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = SampleEffort_yr)) +
  geom_line(linewidth = 0.8) +
  scale_color_manual(values = c("yr1" = "paleturquoise4", 
                                "yr2" = "cadetblue3"),
                     labels = c("year 1",
                                "year 2")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = SampleEffort_yr),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_manual(values = c("yr1" = "paleturquoise4", 
                               "yr2" = "cadetblue3"),
                    labels = c("year 1",
                               "year 2")) +
  geom_point(data = PIPJ_mediantree_pred_thresholds_BOTHYRS,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = SampleEffort_yr),
             size = 2) +
  geom_point(data = PIPJ_data_yr1_full,
             aes(x = CrownDamage_percentvolume +
                   runif(nrow(PIPJ_data_yr1_full), min = -0.75, max = 0.75),
                 y = 0.67),
             shape = "|", 
             size = 2, 
             color = "paleturquoise4") +
  geom_point(data = PIPJ_data_yr2,
             aes(x = CrownDamage_percentvolume +
                   runif(nrow(PIPJ_data_yr2), min = -0.75, max = 0.75),
                 y = 0.6),
             shape = "|", 
             size = 2, 
             color = "cadetblue3") +
  coord_trans(y = "log") +
  scale_y_continuous(limits = c(0.6, 40),
                     breaks = c(0, 5, 10, 20, 30, 40)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  theme_classic() +
  guides(color = guide_legend(title = "Sample year"),
         fill = guide_legend(title = "Sample year")) + 
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none")

PIPJ_mediantree_plot_forpanel


# reformatting the PILA median tree plot...
PILA_mediantree_plot_forpanel <- PILA_mediantree_pred_df_BOTHYRS %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = SampleEffort_yr)) +
  geom_line(linewidth = 0.8) +
  scale_color_manual(values = c("yr1" = "paleturquoise4", 
                                "yr2" = "cadetblue3"),
                     labels = c("year 1", 
                                "year 2")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = SampleEffort_yr),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_manual(values = c("yr1" = "paleturquoise4", 
                               "yr2" = "cadetblue3"),
                    labels = c("year 1",
                               "year 2")) +
  geom_point(data = PILA_mediantree_pred_thresholds_BOTHYRS,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = SampleEffort_yr),
             size = 2) +
  geom_point(data = PILA_data_yr1,
             aes(x = CrownDamage_percentvolume +
                   runif(nrow(PILA_data_yr1), min = -0.75, max = 0.75),
                 y = 1.62),
             shape = "|", 
             size = 2, 
             color = "paleturquoise4") +
  geom_point(data = PILA_data_yr2,
             aes(x = CrownDamage_percentvolume +
                   runif(nrow(PILA_data_yr2), min = -0.75, max = 0.75),
                 y = 1.5),
             shape = "|", 
             size = 2, 
             color = "cadetblue3") +
  coord_trans(y = "log") +
  scale_y_continuous(limits = c(1.5, 40),
                     breaks = c(0, 5, 10, 20, 30, 40)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  theme_classic() +
  guides(color = guide_legend(title = "Sample year"),
         fill = guide_legend(title = "Sample year")) + 
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none")

PILA_mediantree_plot_forpanel


# compiling these three, reformatted median tree plots into a single
# panel (with each plot stacked on top of the other, in a column, and
# labeled according to species)...
mediantree_panel <- plot_grid(ABCO_mediantree_plot_forpanel,
                              PIPJ_mediantree_plot_forpanel,
                              PILA_mediantree_plot_forpanel,
                              ncol = 1,
                              align = "hv",
                              labels = c("white fir", 
                                         "yellow pine", 
                                         "sugar pine"),
                              label_size = 11,
                              label_x = c(0.099, 0.06, 0.07),
                              label_y = 0.32)

mediantree_panel

# adding the median tree legend to the top of this column of plots...
mediantree_panel_wlegend <- plot_grid(mediantree_plot_legend,
                                      mediantree_panel,
                                      ncol = 1,
                                      rel_heights = c(0.03, 1)) +
  theme(plot.background = element_rect(fill = "white", color = NA))

mediantree_panel_wlegend


# exporting this median tree panel plot as both a .png and a .pdf file...
# ggsave(plot = mediantree_panel_wlegend,
#        filename = "results/final/figures/mediantree_panelplot_allspp.png",
#        width = 8.5,
#        height = 22,
#        units = "cm",
#        dpi = 600)

# ggsave(plot = mediantree_panel_wlegend,
#        filename = "results/final/figures/mediantree_panelplot_allspp.pdf",
#        width = 8.5,
#        height = 22,
#        units = "cm",
#        dpi = 600)



## creating a panel plot that displays predicted mean cone counts for the
## 10th, 50th, and 90th percentile-sized ABCOs, PIPJs, and PILAs in both
## the first and second years after fire, with one panel for each species-
## year (and each panel containing three curves - one for each tree size)...

# first, resizing and reformatting each of the species-year-specific 
# interaction plots (originally generated in each iteration of 
# script #6), to be compiled into a single panel plot below....

# reformatting the year 1 ABCO plot...
ABCO_myr1_plot_forpanel <- ABCO_myr1_pred_df %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = DBH_cm_unscaled)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "YlGnBu",
                     labels = c("10th percentile",
                                "50th percentile",
                                "90th percentile")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = DBH_cm_unscaled),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_brewer(palette = "YlGnBu",
                    labels = c("10th percentile",
                               "50th percentile",
                               "90th percentile")) +
  geom_point(data = ABCO_myr1_pred_df_thresholds,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = DBH_cm_unscaled),
             size = 2) +
  geom_rug(data = ABCO_data_yr1_full,
           mapping = aes(x = CrownDamage_percentvolume,
                         y = 25),
           inherit.aes = FALSE,
           sides = "b",
           position = "jitter",
           color = "grey",
           linewidth = 0.3) +
  coord_trans(y = "log") +
  scale_y_continuous(breaks = c(0, 50, 100, 200, 300, 400, 500)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  guides(color = guide_legend(title = "Tree size", 
                              reverse = TRUE),
         fill = guide_legend(title = "Tree size",
                             reverse = TRUE)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 10, face = "bold",
                                    margin = margin (0, 0.6, 0, 0, "cm")),
        legend.text = element_text(size = 8),
        legend.key.spacing.x = unit(0.4, "cm"),
        legend.direction = "horizontal",
        legend.position = "top")

ABCO_myr1_plot_forpanel

# extracting the legend from this reformatted plot, for use in the panel
# below...
intx_plot_legend <- get_legend(ABCO_myr1_plot_forpanel)

# resaving the ABCO_myr1_plot_forpanel without its legend...
ABCO_myr1_plot_forpanel <- ABCO_myr1_plot_forpanel +
  theme(legend.position = "none")

ABCO_myr1_plot_forpanel


# reformatting the year 2 ABCO plot...
ABCO_myr2_plot_forpanel <- ABCO_myr2_pred_df %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = DBH_cm_unscaled)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "YlGnBu",
                     labels = c("10th percentile",
                                "50th percentile",
                                "90th percentile")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = DBH_cm_unscaled),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_brewer(palette = "YlGnBu",
                    labels = c("10th percentile",
                               "50th percentile",
                               "90th percentile")) +
  geom_point(data = ABCO_myr2_pred_df_thresholds,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = DBH_cm_unscaled),
             size = 2) +
  geom_rug(data = ABCO_data_yr2,
           mapping = aes(x = CrownDamage_percentvolume,
                         y = 2),
           inherit.aes = FALSE,
           sides = "b",
           position = "jitter",
           color = "grey",
           linewidth = 0.3) +
  coord_trans(y = "log") +
  scale_y_continuous(limits = c(2, 40.5),
                     breaks = c(0, 5, 10, 20, 30, 40)) +
  xlim(0, 100) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  guides(color = guide_legend(title = "Tree size", 
                              reverse = TRUE),
         fill = guide_legend(title = "Tree size",
                             reverse = TRUE)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none")

ABCO_myr2_plot_forpanel


# reformatting the year 1 PIPJ plot...
PIPJ_myr1_plot_forpanel <- PIPJ_myr1_pred_df %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = DBH_cm_unscaled)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "YlGnBu",
                     labels = c("10th percentile",
                                "50th percentile",
                                "90th percentile")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = DBH_cm_unscaled),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_brewer(palette = "YlGnBu",
                    labels = c("10th percentile",
                               "50th percentile",
                               "90th percentile")) +
  geom_point(data = PIPJ_myr1_pred_df_thresholds,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = DBH_cm_unscaled),
             size = 2) +
  geom_rug(data = PIPJ_data_yr1_full,
           mapping = aes(x = CrownDamage_percentvolume,
                         y = 5),
           inherit.aes = FALSE,
           sides = "b",
           position = "jitter",
           color = "grey",
           linewidth = 0.3) +
  coord_trans(y = "log") +
  scale_y_continuous(breaks = c(0, 5, 10, 20, 30, 40, 50)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  guides(color = guide_legend(title = "Tree size", 
                              reverse = TRUE),
         fill = guide_legend(title = "Tree size",
                             reverse = TRUE)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none")

PIPJ_myr1_plot_forpanel


# reformating the year 2 PIPJ plot...
PIPJ_myr2_plot_forpanel <- PIPJ_myr2_pred_df %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = DBH_cm_unscaled)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "YlGnBu",
                     labels = c("10th percentile",
                                "50th percentile",
                                "90th percentile")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = DBH_cm_unscaled),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_brewer(palette = "YlGnBu",
                    labels = c("10th percentile",
                               "50th percentile",
                               "90th percentile")) +
  geom_point(data = PIPJ_myr2_pred_df_thresholds,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = DBH_cm_unscaled),
             size = 2) +
  geom_rug(data = PIPJ_data_yr2,
           mapping = aes(x = CrownDamage_percentvolume,
                         y = 5),
           inherit.aes = FALSE,
           sides = "b",
           position = "jitter",
           color = "grey",
           linewidth = 0.3) +
  coord_trans(y = "log") +
  scale_y_continuous(breaks = c(0, 5, 10, 20, 30, 50, 70)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  guides(color = guide_legend(title = "Tree size", 
                              reverse = TRUE),
         fill = guide_legend(title = "Tree size",
                             reverse = TRUE)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none")

PIPJ_myr2_plot_forpanel


# reformatting the year 1 PILA plot...
PILA_myr1_plot_forpanel <- PILA_myr1_pred_df %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = DBH_cm_unscaled)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "YlGnBu",
                     labels = c("10th percentile",
                                "50th percentile",
                                "90th percentile")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = DBH_cm_unscaled),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_brewer(palette = "YlGnBu",
                    labels = c("10th percentile",
                               "50th percentile",
                               "90th percentile")) +
  geom_point(data = PILA_myr1_pred_df_thresholds,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = DBH_cm_unscaled),
             size = 2) +
  geom_rug(data = PILA_data_yr1,
           mapping = aes(x = CrownDamage_percentvolume,
                         y = 5),
           inherit.aes = FALSE,
           sides = "b",
           position = "jitter",
           color = "grey",
           linewidth = 0.3) +
  coord_trans(y = "log") +
  scale_y_continuous(breaks = c(0, 5, 10, 20, 40, 60, 80, 100)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  guides(color = guide_legend(title = "Tree size", 
                              reverse = TRUE),
         fill = guide_legend(title = "Tree size",
                             reverse = TRUE)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none")

PILA_myr1_plot_forpanel


# reformatting the year 2 PILA plot...
PILA_myr2_plot_forpanel <- PILA_myr2_pred_df %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = DBH_cm_unscaled)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "YlGnBu",
                     labels = c("10th percentile",
                                "50th percentile",
                                "90th percentile")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = DBH_cm_unscaled),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_brewer(palette = "YlGnBu",
                    labels = c("10th percentile",
                               "50th percentile",
                               "90th percentile")) +
  geom_point(data = PILA_myr2_pred_df_thresholds,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = DBH_cm_unscaled),
             size = 2) +
  geom_rug(data = PILA_data_yr2,
           mapping = aes(x = CrownDamage_percentvolume,
                         y = 5),
           inherit.aes = FALSE,
           sides = "b",
           position = "jitter",
           color = "grey",
           linewidth = 0.3) +
  coord_trans(y = "log") +
  scale_y_continuous(breaks = c(0, 5, 10, 20, 40, 60)) +
  xlim(0, 100) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  guides(color = guide_legend(title = "Tree size", 
                              reverse = TRUE),
         fill = guide_legend(title = "Tree size",
                             reverse = TRUE)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "none")

PILA_myr2_plot_forpanel


# combining all of these individual panels into one big panel plot (3 rows
# by 2 columns), and adding labels...
intx_plot_panel <- plot_grid(ABCO_myr1_plot_forpanel,
                             ABCO_myr2_plot_forpanel,
                             PIPJ_myr1_plot_forpanel,
                             PIPJ_myr2_plot_forpanel,
                             PILA_myr1_plot_forpanel,
                             PILA_myr2_plot_forpanel,
                             nrow = 3,
                             ncol = 2,
                             align = "hv",
                             labels = c("white fir year 1",
                                        "white fir year 2",
                                        "yellow pine year 1",
                                        "yellow pine year 2",
                                        "sugar pine year 1", 
                                        "sugar pine year 2"),
                             label_size = 11,
                             label_x = c(0.03, 0.03,
                                         0, 0,
                                         0, 0),
                             label_y = 0.27)

intx_plot_panel

# adding the interaction plot legend to the top of this panel...
intx_plot_panel_wlegend <- plot_grid(intx_plot_legend,
                                     intx_plot_panel,
                                     nrow = 2,
                                     rel_heights = c(0.05, 1)) +
  theme(plot.background = element_rect(fill = "white", color = NA))

intx_plot_panel_wlegend


# exporting this size-damage interaction panel plot as both a .png and 
# a .pdf file...
# ggsave(plot = intx_plot_panel_wlegend,
#        filename = "results/final/figures/size-damage-intx_panelplot_allspp.png",
#        width = 18,
#        height = 22,
#        units = "cm",
#        dpi = 600)
# 
# ggsave(plot = intx_plot_panel_wlegend,
#        filename = "results/final/figures/size-damage-intx_panelplot_allspp.pdf",
#        width = 18,
#        height = 22,
#        units = "cm",
#        dpi = 600)



## splitting this six panel size-damage interaction plot into two, three
## panel interaction plots (one for each sample year)...

# once again, reformatting the year 1 ABCO plot to generate a smaller
# plot legend...
ABCO_myr1_plot_forpanel_smaller <- ABCO_myr1_pred_df %>% 
  ggplot(aes(x = CrownDamage_percentvolume_unscaled,
             y = fit_backtransformed,
             color = DBH_cm_unscaled)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "YlGnBu",
                     labels = c("10th percentile",
                                "50th percentile",
                                "90th percentile")) +
  geom_ribbon(aes(ymin = CI_lowerlimit,
                  ymax = CI_upperlimit,
                  fill = DBH_cm_unscaled),
              alpha = 0.2,
              linewidth = 0) +
  scale_fill_brewer(palette = "YlGnBu",
                    labels = c("10th percentile",
                               "50th percentile",
                               "90th percentile")) +
  geom_point(data = ABCO_myr1_pred_df_thresholds,
             mapping = aes(x = CrownDamage_percentvolume_unscaled,
                           y = fit_backtransformed,
                           color = DBH_cm_unscaled),
             size = 2) +
  geom_rug(data = ABCO_data_yr1_full,
           mapping = aes(x = CrownDamage_percentvolume,
                         y = 25),
           inherit.aes = FALSE,
           sides = "b",
           position = "jitter",
           color = "grey",
           linewidth = 0.3) +
  coord_trans(y = "log") +
  scale_y_continuous(breaks = c(0, 50, 100, 200, 300, 400, 500)) +
  xlab("Crown volume damage (%)") +
  ylab("Number of cones per tree") +
  guides(color = guide_legend(title = "Tree size", 
                              reverse = TRUE),
         fill = guide_legend(title = "Tree size",
                             reverse = TRUE)) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.title = element_text(size = 8, face = "bold",
                                    margin = margin(0, 0.29, 0, 0, "cm")),
        legend.text = element_text(size = 7,
                                   margin = margin(0, 0, 0, 0.15, "cm")),
        legend.direction = "horizontal",
        legend.key.size = unit(0.4, "cm"),
        legend.key.spacing.x = unit(0.19, "cm"),
        legend.margin = margin(0, 0, 0, 0, "cm"),
        legend.position = "top",
        legend.justification = "center")

ABCO_myr1_plot_forpanel_smaller

# extracting the smaller plot legend for use below...
intx_plot_legend_smaller <- get_legend(ABCO_myr1_plot_forpanel_smaller)


# combining all of the year 1 interaction plots into a single panel
# (one column, with three panels stacked on top of each other)...
intx_plot_panel_yr1 <- plot_grid(ABCO_myr1_plot_forpanel,
                                 PIPJ_myr1_plot_forpanel,
                                 PILA_myr1_plot_forpanel,
                                 ncol = 1,
                                 align = "hv",
                                 labels = c("white fir year 1",
                                            "yellow pine year 1",
                                            "sugar pine year 1"),
                                 label_size = 10,
                                 label_x = c(0.04, 0.01, 0.015),
                                 label_y = 0.27)

intx_plot_panel_yr1

# adding the smaller legend to the top of this year 1 panel plot...
intx_plot_panel_yr1_wlegend <- plot_grid(intx_plot_legend_smaller,
                                         intx_plot_panel_yr1,
                                         ncol = 1,
                                         rel_heights = c(0.05, 1)) +
  theme(plot.background = element_rect(fill = "white", color = NA))

intx_plot_panel_yr1_wlegend

# exporting this year 1 size-damage interaction panel plot as both a .png and 
# a .pdf file...
# ggsave(plot = intx_plot_panel_yr1_wlegend,
#        filename = "results/final/figures/size-damage-intx_yr1_panelplot_allspp.png",
#        width = 8.5,
#        height = 22,
#        units = "cm",
#        dpi = 600)
# 
# ggsave(plot = intx_plot_panel_yr1_wlegend,
#        filename = "results/final/figures/size-damage-intx_yr1_panelplot_allspp.pdf",
#        width = 8.5,
#        height = 22,
#        units = "cm",
#        dpi = 600)


# doing the same thing for the year 2 interaction plots...
intx_plot_panel_yr2 <- plot_grid(ABCO_myr2_plot_forpanel,
                                 PIPJ_myr2_plot_forpanel,
                                 PILA_myr2_plot_forpanel,
                                 ncol = 1,
                                 align = "hv",
                                 labels = c("white fir year 2",
                                            "yellow pine year 2",
                                            "sugar pine year 2"),
                                 label_size = 10,
                                 label_x = c(0.022, -0.01, 0),
                                 label_y = 0.27)

intx_plot_panel_yr2

# adding the smaller legend to the top of the year 2 panel plot...
intx_plot_panel_yr2_wlegend <- plot_grid(intx_plot_legend_smaller,
                                         intx_plot_panel_yr2,
                                         ncol = 1,
                                         rel_heights = c(0.05, 1)) +
  theme(plot.background = element_rect(fill = "white", color = NA))

intx_plot_panel_yr2_wlegend

# exporting the year 2 size-damage interaction panel plot as both a .png and 
# a .pdf file...
# ggsave(plot = intx_plot_panel_yr2_wlegend,
#        filename = "results/final/figures/size-damage-intx_yr2_panelplot_allspp.png",
#        width = 8.5,
#        height = 22,
#        units = "cm",
#        dpi = 600)
# 
# ggsave(plot = intx_plot_panel_yr2_wlegend,
#        filename = "results/final/figures/size-damage-intx_yr2_panelplot_allspp.pdf",
#        width = 8.5,
#        height = 22,
#        units = "cm",
#        dpi = 600)



## finally, reformatting the PILA_myr1_plot (displaying results for the only
## species-year base model for which the interaction term (DBH:CrownDamage)
## was found to be significant) for publication as a single, standalone
## panel...
PILA_myr1_plot_small <- plot_grid(intx_plot_legend_smaller,
                                  PILA_myr1_plot_forpanel,
                                  ncol = 1,
                                  rel_heights = c(0.1, 1),
                                  labels = c("", 
                                             "sugar pine year 1"),
                                  label_size = 10,
                                  label_x = 0.018,
                                  label_y = 0.26) +
  theme(plot.background = element_rect(fill = "white", color = NA))

PILA_myr1_plot_small

# exporting this reformatted PILA_myr1_plot as both a .png and .pdf file...
# ggsave(plot = PILA_myr1_plot_small,
#        filename = "results/final/figures/PILA_yr1_plot_small.png",
#        width = 8.5,
#        height = 8,
#        units = "cm",
#        dpi = 600)
# 
# ggsave(plot = PILA_myr1_plot_small,
#        filename = "results/final/figures/PILA_yr1_plot_small.pdf",
#        width = 8.5,
#        height = 8,
#        units = "cm",
#        dpi = 600)




